// <auto-generated />
using GancewskaKerebinska.CeramicsCatalogue.DAO.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAO.Migrations
{
    [DbContext(typeof(CeramicsDbContext))]
    [Migration("20251219125420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("GancewskaKerebinska.CeramicsCatalogue.DAO.Entities.CeramicItemDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CeramicType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiringType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProducerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProducerId");

                    b.ToTable("CeramicItems");
                });

            modelBuilder.Entity("GancewskaKerebinska.CeramicsCatalogue.DAO.Entities.ProducerDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("GancewskaKerebinska.CeramicsCatalogue.DAO.Entities.CeramicItemDo", b =>
                {
                    b.HasOne("GancewskaKerebinska.CeramicsCatalogue.DAO.Entities.ProducerDo", "Producer")
                        .WithMany("CeramicItems")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("GancewskaKerebinska.CeramicsCatalogue.DAO.Entities.ProducerDo", b =>
                {
                    b.Navigation("CeramicItems");
                });
#pragma warning restore 612, 618
        }
    }
}
